using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Http;
using System.Web.Http.Controllers;
using System.Web.Http.Filters;
using System.Net.Http;
using NHateoas.Configuration;
using NHateoas.Routes;

namespace NHateoas.Attributes
{

    [AttributeUsage(AttributeTargets.Method)]
    public class HypermediaAttribute : ActionFilterAttribute
    {
        private string[] _names = {};

        /// <summary>
        /// Contain names for specified action. Names will be used as rel, action name or route name instead of autogenerated one
        /// </summary>
        public string[] Names
        {
            get { return _names; }
            set { _names = value; }
        }

        public override void OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
        {
            var content = ActionResponseTransformer.Transform(actionExecutedContext);
            
            if (content == null)
                return;
            
            actionExecutedContext.Response.Content = content;
        }
    }
}
